version: '3.8'

services:
  app:
    # Uncomment for local build:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # Use pre-built image from Docker Hub:
    image: rofiq02bae/laravel-vite-app:latest
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  db_data:
  jenkins_home: